import { readFileSync, writeFileSync } from 'node:fs';

const source = readFileSync(new URL('../src/swedish-calendar.js', import.meta.url), 'utf8');
const factoryMarker = "})(typeof self !== 'undefined' ? self : this, function () {\n";
const factoryStart = source.indexOf(factoryMarker);
const exportStart = source.lastIndexOf('    return {\n');
const factoryEnd = source.lastIndexOf('\n});');

if (factoryStart === -1 || exportStart < factoryStart || factoryEnd < exportStart) {
    throw new Error('Cannot locate the SwedishCalendar factory and API exports.');
}

const body = source.slice(factoryStart + factoryMarker.length, exportStart);
const api = source.slice(exportStart + '    return {\n'.length, factoryEnd);
const names = api.slice(0, api.lastIndexOf('    };')).replace(/^ {8}/gm, '    ');
const output =
    '// Generated by scripts/build-esm.mjs from src/swedish-calendar.js. Do not edit directly.\n' +
    'const SwedishCalendar = (function () {\n' +
    body +
    '    return {\n' +
    api +
    '\n})();\n\nexport const {\n' +
    names +
    '} = SwedishCalendar;\n\nexport default SwedishCalendar;\n';
const destination = new URL('../src/swedish-calendar.mjs', import.meta.url);

if (process.argv.includes('--check')) {
    if (readFileSync(destination, 'utf8') !== output) {
        throw new Error('ESM output is stale. Run npm run build:esm.');
    }
} else {
    writeFileSync(destination, output);
}
